SETTINGS:
  HOST: https://matsuhub.herokuapp.com/
  PORT: 80

LIBS:
  css: "static/lib/metro/css/metro-all.css"
  js: "static/lib/metro/js/metro.js"
  img: "static/lib/img"

ROUTES:
  base: '/'
  login: '/login'
  home: '/home'
  documents: '/home/documents'
  music: '/home/music'
  images: '/home/images'
