SETTINGS:
  HOST: https://matsuhub.herokuapp.com/
  PORT: 80

LIBS:
  css: "static/lib/metro/css/metro-all.css"
  js: "static/lib/metro/js/metro.js"
  img: "static/lib/img"

MUSIC-FILES: "static/home/music"

DOCUMENTS-FILES: "static/home/documents"

IMAGES-FILES:
  family: "static/home/images/family"
  doggys: "static/home/images/doggys"
  partys: "static/home/images/partys"
   
ROUTES:
  base: '/'
  login: '/login'
  home: '/home'
  documents: '/home/documents'
  music: '/home/music'
  images: '/home/images'
